"""ECoG finger-trajectory decoding utilities."""

from .io import BAD_CHANNELS_ONE_BASED, SubjectData, load_subject
from .models import (
    CausalDilatedTCN,
    CausalDilatedTCNBlock,
    DiagonalSSM,
    DiagonalSSMBlock,
    CausalLinearAttention,
    CausalLinearAttentionBlock,
    MambaSequence,
    DilatedWaveletFilterBank,
    EcogTrajectoryDecoder,
    WaveletPacketEnergy,
    compact_wavelet_taps,
    fit_fastica_spatial_weights,
    fixed_length_wavelet_taps,
)
from .spectrotemporal import (
    ContinuousMorletDecoder,
    GroupedTopKAtomGate,
    HilbertQuadrature,
    MorletAtomBank,
    SoftScaleSpectroTemporalConv2d,
    SpectroTemporalWaveletDecoder,
    WaveletPacketSpectrogram,
    analytic_signal,
    label_independent_morlet_centers,
    wavelet_packet_frequency_order,
)
from .preprocessing import (
    BaselineResult,
    EcogResult,
    MovementCorrectionModel,
    MovementCorrectionResult,
    apply_movement_corrector,
    asymmetric_baseline,
    baseline_correct,
    downsample_glove,
    fit_movement_corrector,
    local_baseline_correct,
    local_lower_envelope_baseline,
    preprocess_ecog,
)
from .postprocessing import fit_nonnegative_gain, project_nonnegative, smooth_nonnegative

__all__ = [
    "BAD_CHANNELS_ONE_BASED",
    "BaselineResult",
    "CausalDilatedTCN",
    "CausalDilatedTCNBlock",
    "DiagonalSSM",
    "DiagonalSSMBlock",
    "CausalLinearAttention",
    "CausalLinearAttentionBlock",
    "MambaSequence",
    "EcogResult",
    "DilatedWaveletFilterBank",
    "EcogTrajectoryDecoder",
    "ContinuousMorletDecoder",
    "GroupedTopKAtomGate",
    "HilbertQuadrature",
    "MorletAtomBank",
    "MovementCorrectionModel",
    "MovementCorrectionResult",
    "SubjectData",
    "SoftScaleSpectroTemporalConv2d",
    "SpectroTemporalWaveletDecoder",
    "WaveletPacketEnergy",
    "WaveletPacketSpectrogram",
    "analytic_signal",
    "label_independent_morlet_centers",
    "apply_movement_corrector",
    "asymmetric_baseline",
    "baseline_correct",
    "compact_wavelet_taps",
    "fit_fastica_spatial_weights",
    "fixed_length_wavelet_taps",
    "downsample_glove",
    "fit_movement_corrector",
    "fit_nonnegative_gain",
    "load_subject",
    "local_baseline_correct",
    "local_lower_envelope_baseline",
    "preprocess_ecog",
    "project_nonnegative",
    "smooth_nonnegative",
    "wavelet_packet_frequency_order",
]
