"""ECoG finger-trajectory decoding utilities."""

from .io import BAD_CHANNELS_ONE_BASED, SubjectData, load_subject
from .models import (
    CausalDilatedTCN,
    CausalDilatedTCNBlock,
    DiagonalSSM,
    DiagonalSSMBlock,
    CausalLinearAttention,
    CausalLinearAttentionBlock,
    MambaSequence,
    DilatedWaveletFilterBank,
    EcogTrajectoryDecoder,
    WaveletPacketEnergy,
    compact_wavelet_taps,
    fit_fastica_spatial_weights,
    fixed_length_wavelet_taps,
)
from .preprocessing import (
    BaselineResult,
    EcogResult,
    MovementCorrectionModel,
    MovementCorrectionResult,
    apply_movement_corrector,
    asymmetric_baseline,
    baseline_correct,
    downsample_glove,
    fit_movement_corrector,
    local_baseline_correct,
    local_lower_envelope_baseline,
    preprocess_ecog,
)

__all__ = [
    "BAD_CHANNELS_ONE_BASED",
    "BaselineResult",
    "CausalDilatedTCN",
    "CausalDilatedTCNBlock",
    "DiagonalSSM",
    "DiagonalSSMBlock",
    "CausalLinearAttention",
    "CausalLinearAttentionBlock",
    "MambaSequence",
    "EcogResult",
    "DilatedWaveletFilterBank",
    "EcogTrajectoryDecoder",
    "MovementCorrectionModel",
    "MovementCorrectionResult",
    "SubjectData",
    "WaveletPacketEnergy",
    "apply_movement_corrector",
    "asymmetric_baseline",
    "baseline_correct",
    "compact_wavelet_taps",
    "fit_fastica_spatial_weights",
    "fixed_length_wavelet_taps",
    "downsample_glove",
    "fit_movement_corrector",
    "load_subject",
    "local_baseline_correct",
    "local_lower_envelope_baseline",
    "preprocess_ecog",
]
